language: java
sudo: false
script: mvn clean install --fail-at-end
notifications:
  email:
    on_failure: true
matrix:
  include:
  - jdk: openjdk6
    env: JACOCO=true COVERALLS=true
  - jdk: openjdk7
    env: JACOCO=true COVERALLS=true
  - jdk: oraclejdk7
    env: JACOCO=true COVERALLS=true
  - jdk: oraclejdk8
    env: JACOCO=true COVERALLS=true
  - jdk: openjdk7
    env: JACOCO=true GDMSESSION=sonar SONAR_ANALYSIS_MODE=publish
    script: mvn clean install -Dsonar.analysis.mode=publish --fail-at-end
  - jdk: openjdk6
    env: JACOCO=false
  - jdk: openjdk7
    env: JACOCO=false
  - jdk: oraclejdk7
    env: JACOCO=false
  - jdk: oraclejdk8
    env: JACOCO=false
