language: java
dist: trusty
before_script: mvn dependency:go-offline
script: mvn clean verify --fail-at-end
notifications:
  email:
    on_failure: change
matrix:
  include:
    # Quality testing
    - jdk: oraclejdk8
      env: JACOCO=true RELEASE_CHECKS=true
    - jdk: oraclejdk8
      env: JACOCO=true COVERALLS=true
    - jdk: oraclejdk8
      env: JACOCO=true SONAR=publish
      script: mvn clean verify sonar:sonar --fail-at-end
    # Performance testing
    - jdk: openjdk7
      env: JACOCO=false
    - jdk: openjdk8
      env: JACOCO=false
    - jdk: oraclejdk9
      env: JACOCO=false
    - jdk: oraclejdk11
      env: JACOCO=false
